import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} 
      ${geistMono.variable}`}
      >
        <div className="bg-orange-50 text-gray-800 min-h-screen flex flex-col">
          {/* Header */}
          <header className="bg-orange-400 p-4 shadow-md">
            <h1 className="text-3xl font-bold text-center text-orange-1000">
              Solar Splash
            </h1>
            <p className="text-center text-orange-800 text-sm">
              Pure Energy, Pure Sunshine.
            </p>
          </header>

          {/* Main Content */}

          <main className="flex-1 p-6 text-center flex justify-center">
            {children}
          </main>

          {/* Footer */}
          <footer className="bg-orange-300 p-4 text-center text-sm text-orange-800">
            &copy; 2025 Solar Splash. Stay Refreshed!
          </footer>
        </div>
      </body>
    </html>
  );
}
